// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9nTiFTC_hjKqLYFsgsbSPY3P8EYuuFtw',
    appId: '1:269395620684:web:71ef94b42961e558e195e9',
    messagingSenderId: '269395620684',
    projectId: 'expense-tracker-db-6acc9',
    authDomain: 'expense-tracker-db-6acc9.firebaseapp.com',
    storageBucket: 'expense-tracker-db-6acc9.firebasestorage.app',
    measurementId: 'G-KF1H12MMPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGZ2GJf9Z_1EV0wc_hhLFugnd9-pw0WRw',
    appId: '1:269395620684:android:c7244daae1c6d641e195e9',
    messagingSenderId: '269395620684',
    projectId: 'expense-tracker-db-6acc9',
    storageBucket: 'expense-tracker-db-6acc9.firebasestorage.app',
  );

}